In [1]:
import numpy as np
import random

In [2]:
# 1. Create Numpy Arrays:

In [3]:
#1.1 Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.
x=[[1,2,3],[4,5,6]]

In [4]:
np.array(x)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#1.2 Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6

In [6]:
np.arange(1,7).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
#1.3 Use one line to create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.

In [8]:
x=np.arange(2,100,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
np.mean(x)

50.0

In [10]:
#1.4 Create an 3x3x3 array filled with arbitrary float numbers; and find the minimum and maximum values

In [11]:
y=np.random.rand(3,3,3)
y

array([[[0.37806511, 0.84387847, 0.76284588],
        [0.94958701, 0.67791088, 0.80478005],
        [0.66078296, 0.76753587, 0.08476118]],

       [[0.31388979, 0.80507714, 0.19155887],
        [0.12436396, 0.30904025, 0.89504729],
        [0.36486368, 0.74608112, 0.55692462]],

       [[0.01271998, 0.2918988 , 0.49738565],
        [0.02816585, 0.01317285, 0.7912464 ],
        [0.10238385, 0.63397894, 0.4723216 ]]])

In [12]:
np.min(y)

0.012719983704722493

In [13]:
np.max(y)

0.9495870116666519

In [14]:
#1.5 Create a 3x4 2D array filled with values from 10 to 21 (included). 

In [15]:
np.arange(10,22).reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [16]:
#1.6 Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.

In [75]:
#solution 1
np.arange(5,11*3, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [18]:
#solution 2
np.arange(0,10)*3+5

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [164]:
#1.7 Create a shape (10,10) array with arbitrary values; and find the memory size of this array.
x1= np.random.randint(10, size=(10, 10))
#x1=np.random.rand(10,10)
x1

array([[7, 6, 0, 3, 9, 4, 4, 6, 8, 4],
       [9, 2, 1, 1, 6, 3, 4, 5, 4, 0],
       [2, 8, 0, 7, 6, 5, 8, 2, 2, 0],
       [1, 2, 3, 5, 7, 8, 7, 7, 6, 9],
       [2, 0, 4, 5, 4, 6, 9, 0, 4, 6],
       [4, 9, 8, 0, 7, 1, 7, 1, 1, 5],
       [5, 0, 8, 3, 7, 1, 5, 2, 3, 4],
       [5, 7, 6, 8, 0, 4, 6, 3, 5, 9],
       [3, 8, 3, 0, 9, 6, 2, 3, 9, 1],
       [4, 0, 5, 0, 8, 1, 3, 6, 0, 0]])

In [71]:
x1.nbytes

800

In [21]:
#1.8 Create a 1-d array of size 10 with arbitrary values but the fifth value should be 5

In [22]:
x2= np.zeros(10, dtype=int)
x2[4]= 5
x2

array([0, 0, 0, 0, 5, 0, 0, 0, 0, 0])

In [23]:
#1.9 Create an array with values ranging from 10 to 49 (included); and reverse it then (first element becomes last).

In [24]:
x3= np.arange(10,50)
x3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [25]:
x3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [83]:
#1.10 Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and 
#confirm you can get the same value when you run it next time

In [82]:
np.random.seed(10)
np.random.normal(0,1, size=(3, 2))

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556]])

In [28]:
#1.11 Create a 5x5 matrix with row values ranging from 0 to 4

In [29]:
np.zeros((5,5), dtype=int)+np.arange(5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [30]:
#1.12 Add a border (filled with 0's) around an existing array:

In [31]:
x6 = np.ones((5,5))
x6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.pad(x6, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [33]:
#1.13 Create a 5x5 2-d array with values 1,2,3,4,5 on the diagonal (3 points)

In [34]:
#1.13.1
x7=np.zeros([5, 5])
x7[np.arange(0, 5), np.arange(0, 5)] = [1,2,3,4,5]
x7

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [35]:
#1.13.2
x7[np.arange(0, 5), np.arange(0, 5)] = 0
x7[np.arange(1, 5), np.arange(0, 4)] = [1,2,3,4]
x7

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [84]:
#1.14 Create a 10x10 2-d array with 1 (2 point) on the border and 0 inside (4 points).

In [37]:
x8=np.ones([10, 10], dtype=int)
x8

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [38]:
x8[1:9, 1:9]=0
x8

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [39]:
#1.15 Extract the integer part of a random array of positive numbers using 2 different methods, 
#and the result should be an integer array.
d = np.random.uniform(0,5,(2,10))
d

array([[3.85660322, 0.10375975, 3.16824117, 3.74401941, 2.49253506,
        1.12398323, 0.99031432, 3.80265356, 0.84555418, 0.44169907],
       [3.42679909, 4.76696673, 0.01974133, 2.56096132, 4.06310481,
        3.06263033, 3.60877659, 1.45938034, 4.58887061, 3.57287892]])

In [40]:
#Method 1
d.astype(int)

array([[3, 0, 3, 3, 2, 1, 0, 3, 0, 0],
       [3, 4, 0, 2, 4, 3, 3, 1, 4, 3]])

In [41]:
#Method 2
np.asarray(d,dtype="int")

array([[3, 0, 3, 3, 2, 1, 0, 3, 0, 0],
       [3, 4, 0, 2, 4, 3, 3, 1, 4, 3]])

In [42]:
#2. Operations on Numpy Arrays:

In [160]:
#2.1 Find the index of 5th repetition of number 1 in the given array x.
#x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
xy= np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
xy

array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [162]:
np.where(xy==1)[0][4]

8

In [44]:
#2.2 Use np.arange to get an array [1, 2, 3, ..., 9]. Split x into 3 sub-arrays, 
#the length of each sub-array is 4, 2, and 3.
y1 = np.arange(1,10)
y1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.split(y1, [4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

In [46]:
# 2.3 Use np.arange to generate the following 2D array:               

# [[ 0., 1., 2., 3.],

#  [ 4., 5., 6., 7.],

#  [ 8., 9., 10., 11.],

# #  [ 12., 13., 14., 15.]]
# Use np.split to split the array into left and right halves.

# [[ 0,  1],

#  [ 4,  5],

#  [ 8,  9],

#  [12, 13]]

# and

# [[ 2,  3],

#  [ 6,  7],

#  [10, 11],

#  [14, 15]]

In [47]:
y2= np.arange(0,16,dtype=float).reshape(4,4)
y2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [48]:
np.split(y2, 2, 1)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [49]:
#2.4 Given an 2D array:                                               

# [[5,10,15],

#  [20,25,30],

#  [35,40,45]]

# (1) Slicing to get the sub-array [[10,15], [25,30]]

# (2) Getting individual element value "20" 


In [50]:
y3= np.array([[5,10,15],[20,25,30],[35,40,45]])
y3

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
y3[0:2, 1:4]

array([[10, 15],
       [25, 30]])

In [52]:
y3[1][0]

20

In [53]:
# 2.5 Let x be an array:                                                   

# [[ 1 2 3],

#  [ 4 5 6]].
# and y be an array

# [[ 7 8 9],

#  [10 11 12]].
# Concatenate x and y so that a new array looks like

# [[1, 2, 3, 7, 8, 9],

#  [4, 5, 6, 10, 11, 12]].

In [54]:
y4= np.array([[ 1,2, 3],[ 4,5,6]])
y5= np.array([[ 7,8,9],[10,11,12]])
print(y4)
print(y5)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [55]:
np.concatenate((y4, y5)).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [91]:
#2.6 Compute the min/max (min is divided by max) for each row for a given 2d array, in which integer values 
#range from 1 to 10 [1,10) and shape is (5,3).
# Here requires a random seed to keep the same value from the random generator.

In [92]:
np.random.seed(10)
y6=np.random.randint(10, size=(5,3))
y6

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

In [98]:
for i in range(5):
    print(np.min(y6[i])/np.max(y6[i]))

0.0
0.0
0.1111111111111111
0.0
0.0


In [57]:
#2.7 Normalize a 5x5 random matrix:                         

# Tips: a normalization operates like: (the array - the mean)/the standard deviation

In [113]:
y7=np.random.randint(10,size=(5,5))
y7

array([[1, 8, 9, 1, 2],
       [8, 9, 9, 5, 0],
       [2, 7, 3, 0, 4],
       [2, 0, 3, 3, 1],
       [2, 5, 9, 0, 1]])

In [115]:
y7- np.mean(y7)/np.std(y7)

array([[-0.16467292,  6.83532708,  7.83532708, -0.16467292,  0.83532708],
       [ 6.83532708,  7.83532708,  7.83532708,  3.83532708, -1.16467292],
       [ 0.83532708,  5.83532708,  1.83532708, -1.16467292,  2.83532708],
       [ 0.83532708, -1.16467292,  1.83532708,  1.83532708, -0.16467292],
       [ 0.83532708,  3.83532708,  7.83532708, -1.16467292, -0.16467292]])

In [58]:
#2.8 Convert 3 arrays into a 1d array.                         

# arr1: 0,1,2

# arr2: 3,4,5,6

# arr3: 7,8,9
# Generate the 3 arrays by numpy arange()

# Desired Output:

# ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [59]:
arr1 = np.arange(0,3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
print(arr1)
print(arr2)
print(arr3)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [60]:
np.concatenate((arr1, arr2, arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
#2.9 Get all items between 15 and 55 from aa, math expression: [15,55].                 

# The aa is uniformly distributed integers in a 1D array (size=20) with given values (<100). 
# Requires defining a seed.
np.random.seed(10)
y9= np.random.randint(100, size=20)
y9

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0, 40, 36, 16, 11, 54, 88, 62,
       33, 72, 78])

In [179]:
indices=np.where(np.logical_and(y9>=15, y9<=55))
y9[indices]

array([15, 28, 29, 40, 36, 16, 54, 33])

In [146]:
#2.10 Get the positions where elements of a and b match.                

arr_a = np.array([1,2,3,2,3,4,3,4,5,6])

arr_b = np.array([7,2,10,2,7,4,9,4,9,8])
print(arr_a)
print(arr_b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [211]:
arrabVal, arra_idx, arrb_idx = np.intersect1d(arr_a, arr_b,return_indices=True)
print(arra_idx)

[1 5]


In [63]:
#2.11 Use arange() to create an array from 0 to 20 ( [0,20) ); replace all odd numbers with -1.

In [167]:
y8= np.arange(0,20)
y8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [122]:
y8[1::2]=-1
y8

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

In [64]:
#2.12 Considering a four dimensions array (3,4,3,4) with the values 0-9 randomly, 
#how to get sum over the last two axis at once?

In [195]:
y9=np.random.randint(9,size=(3,4,3,4))
y9


array([[[[8, 6, 6, 4],
         [7, 1, 4, 1],
         [4, 6, 8, 7]],

        [[6, 3, 4, 3],
         [5, 2, 0, 7],
         [0, 3, 4, 8]],

        [[1, 4, 7, 7],
         [4, 0, 5, 1],
         [5, 4, 8, 2]],

        [[7, 2, 4, 2],
         [5, 7, 3, 3],
         [1, 7, 5, 1]]],


       [[[4, 8, 0, 6],
         [5, 4, 3, 5],
         [6, 2, 3, 4]],

        [[7, 2, 0, 2],
         [5, 5, 1, 4],
         [4, 8, 7, 0]],

        [[7, 4, 8, 5],
         [7, 5, 2, 1],
         [6, 2, 8, 4]],

        [[0, 4, 2, 3],
         [6, 4, 8, 6],
         [1, 1, 3, 8]]],


       [[[6, 5, 5, 8],
         [6, 3, 0, 4],
         [2, 7, 4, 7]],

        [[2, 6, 0, 1],
         [5, 8, 3, 5],
         [6, 6, 4, 4]],

        [[0, 3, 1, 7],
         [0, 3, 7, 4],
         [4, 2, 1, 3]],

        [[1, 2, 8, 8],
         [6, 8, 2, 1],
         [5, 6, 1, 7]]]])

In [210]:
np.sum(sum(y7))

94

In [207]:
np.sum(y9, axis=-3)

array([[[22, 15, 21, 16],
        [21, 10, 12, 12],
        [10, 20, 25, 18]],

       [[18, 18, 10, 16],
        [23, 18, 14, 16],
        [17, 13, 21, 16]],

       [[ 9, 16, 14, 24],
        [17, 22, 12, 14],
        [17, 21, 10, 21]]])

In [208]:
np.sum(y9, axis=-2)

array([[[19, 13, 18, 12],
        [11,  8,  8, 18],
        [10,  8, 20, 10],
        [13, 16, 12,  6]],

       [[15, 14,  6, 15],
        [16, 15,  8,  6],
        [20, 11, 18, 10],
        [ 7,  9, 13, 17]],

       [[14, 15,  9, 19],
        [13, 20,  7, 10],
        [ 4,  8,  9, 14],
        [12, 16, 11, 16]]])